### ISSUE TITLE
Feature Requests: More available commands/args support.

### ISSUE THREAD

**Issue by ZiqiYang394** [yuudi/rclone-webui-angular#44]
Hi yuudi,

Firstly really thanks for such excellent GUI support of rclone. In the original rclone, there are many additional commands/args support, such as mounting the specific path as the root dir, or args like --dir-cache-time or --vfs-cache-mode, etc. I can understand that it might be difficult to show each available args as a selectable option in the GUI, but is it possible to add a text zone to allow input manually, and directly load args from texts?

![Screenshot 2024-10-22 223612](https://github.com/user-attachments/assets/02d645c4-7a51-42b8-b6c4-ef040a916610)
As shown in this pic, add a text input zone to accept customised args input. If the user input wrong args or commands here, just return the original error message in a message box.

Many thanks,
Ziqi

**Comment by yuudi** [comment]
Yes this is not a hard work. I can add a custom flags area here. It won't be not like args format but json format, because the remote control API is different. I will put a link to the document near the input box as well.

**Comment by yuudi** [comment]
Done at version 0.8.0
