### ISSUE TITLE
增加运行web-gui后自动挂载的功能

### ISSUE THREAD

**Issue by qq392784506** [yuudi/rclone-webui-angular#8]
现在需要到挂载页面中，关闭挂载（提示mount not fonud），再打开挂载，才能挂载到本地磁盘

**Comment by qq392784506** [comment]
discussions 6#看到了

**Comment by yuudi** [comment]
implemented at [v0.5.0](https://github.com/yuudi/rclone-webui-angular/releases/tag/v0.5.0)
